Add ButterCMS REST API checks
cksource/tiugo-monitoring pull request #42
Opened 2024-10-07 13:45 UTC by LukaszGudel

## Changelog

```
feature: Add ButterCMS REST API checks

Add 3 new checks that are testing CRUD operations from ButterCMS REST API.

Touches: #39.
```

## Linked issues

-  Touches: #39.

2024-10-08 08:59 UTC, dpawlowski-cksource requested changes
WDYT about writing down these new 3 checks (tests) as scenarios (bulletpoints) and ask ButterCMS team on Slack whether they see any performance risks or database clogging when we will run such tests every X minutes?

2024-10-08 08:59 UTC, dpawlowski-cksource commented on src/checksSuites/ButterCMSStatusCheck/ButterCMSPagesStatusCheck.ts
> +		assert( getPage.status === 200, new RequestFailError( getPage ) );
What about creating a new page?

2024-10-08 08:59 UTC, dpawlowski-cksource commented on src/checksSuites/ButterCMSStatusCheck/ButterCMSPagesStatusCheck.ts
> +		await this.delay( 1000 );
I think `waitUntil` is safer approach: https://github.com/cksource/cs/blob/master/cs-e2e-tests/src/chaos-tests/DocumentsStorageChaosTests.ts#L89

2024-10-08 08:59 UTC, dpawlowski-cksource commented on src/checksSuites/ButterCMSStatusCheck/ButterCMSPagesStatusCheck.ts
> +		assert( getPage.status === 200, new RequestFailError( getPage ) );
Are we able to do create / update / get / delete operations?

2024-10-08 08:59 UTC, dpawlowski-cksource commented on src/checksSuites/ButterCMSStatusCheck/ButterCMSPagesStatusCheck.ts
> +		assert( getPage.status === 200, new RequestFailError( getPage ) );
Exactly like you did for collections and posts 🙂 ☝️

2024-10-08 08:59 UTC, dpawlowski-cksource commented on src/checksSuites/ButterCMSStatusCheck/ButterCMSCollectionsStatusCheck.ts
> +		// const body: string = `<h1>New post from Tiugo monitoring</h1><p>${ timestamp }</p>`;
these comments are leftovers?

2024-10-08 08:59 UTC, dpawlowski-cksource commented on src/common/getChecks.ts
> +			productName: 'posts'
IMO this check definition can be inside `....StatusCheck` constructor as it's not dynamic 🙂

2024-10-08 09:10 UTC, LukaszGudel commented on src/checksSuites/ButterCMSStatusCheck/ButterCMSStatusCheck.ts
> +	const secretName = 'BUTTERCMS_API_KEY';
I will check it. Using cs module in tiugo-monitoring will require NPM token, but I think we could copy the class tho and modify it a little to allow using `process.env` for local development 🤔

2024-10-08 09:15 UTC, LukaszGudel commented on src/checksSuites/ButterCMSStatusCheck/ButterCMSPagesStatusCheck.ts
> +		assert( getPage.status === 200, new RequestFailError( getPage ) );
Yes, this requires creating page content type and a page manually in ButterCMS dashboard. There is no REST API endpoint (docs: https://buttercms.com/docs/api/#the-page-object) for deleting pages, so I limited the pages test to get/update/get only, as creating them without the ability to clean them up would quickly create a lot of junk

2024-10-08 09:39 UTC, LukaszGudel commented on src/common/getChecks.ts
> +			productName: 'posts'
There were no new properties needed for ButterCMS status checks and we are using base `CheckDefinition`. Do you think it will be better to create `ButterCMSPostsStatusCheckDefinition`, `ButterCMSBlogsStatusCheckDefinition` and `ButterCMSCollectionsStatusCheckDefinition` classes to define these labels there?

2024-10-08 09:43 UTC, LukaszGudel commented
> WDYT about writing down these new 3 checks (tests) as scenarios (bulletpoints) and ask ButterCMS team on Slack whether they see any performance risks or database clogging when we will run such tests every X minutes?

I want to run these tests against `staging.buttercms.com` for a few days ([env variable with url](https://github.com/cksource/cs/pull/20635/files)) to make sure these test will not affect their systems. I think we can first run it on staging, then check metrics/logs and then additionally consult with them having some more concrete data

2024-10-09 06:36 UTC, dpawlowski-cksource reviewed
Only one suggestion. The rest of the thing LGTM ✅

2024-10-09 06:36 UTC, dpawlowski-cksource commented on src/checksSuites/ButterCMSStatusCheck/ButterCMSStatusCheck.ts
> +				reject( returnedError );
```suggestion
				reject( returnedError ?? new Error(`Wait until timeout. Callback was executed longer than specified ${ timeout } ms timeout`);
```

What if `await callback()` will never throw 🙂 ? IMO we will reject without error. This could be solution 🙂 ☝️

2024-10-09 07:13 UTC, dpawlowski-cksource approved these changes

2024-10-09 09:37 UTC, vokiel approved these changes

2024-10-09 10:26 UTC, merged